import DashboardNavbar from "@/components/dashboard-navbar";
import { createClient } from "../../../../../supabase/server";
import { redirect } from "next/navigation";
import Link from "next/link";
import { BarChart2, TrendingUp, MessageSquare, Clock, Mic, Target, Lightbulb, ChevronLeft } from "lucide-react";

export default async function AIFeedbackPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return redirect("/sign-in");

  // Mock AI analysis data — in production this would be generated by OpenAI after session ends
  const feedback = {
    sessionTopic: "Python Basics: Variables & Functions",
    duration: "47 minutes",
    speakingTimeMe: 35,
    speakingTimeThem: 65,
    clarityScore: 82,
    interactionScore: 75,
    engagementScore: 88,
    keyPoints: [
      "Covered Python variable scoping (local vs global vs nonlocal)",
      "Demonstrated mutable vs immutable data types with examples",
      "Explained function parameters, args, and kwargs",
      "Introduced list comprehensions as a Pythonic pattern",
      "Discussed best practices: snake_case naming conventions",
    ],
    improvements: [
      "You spoke 65% of the time — try asking more questions to encourage your partner",
      "Consider using more visual examples or screen sharing for code demonstrations",
      "Great clarity on variable scope! Your syntax explanations were easy to follow",
      "Try to summarize key points at the end of each topic section",
    ],
    overallScore: 81,
  };

  const getScoreColor = (score: number) => {
    if (score >= 80) return "#38A169";
    if (score >= 60) return "#D69E2E";
    return "#E53E3E";
  };

  return (
    <div className="min-h-screen" style={{ backgroundColor: "#0F1F35" }}>
      <DashboardNavbar />
      <main className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="mb-8">
          <Link href="/dashboard/sessions" className="flex items-center gap-1 text-sm text-[#A0AEC0] hover:text-[#EDF2F7] mb-4 transition-colors">
            <ChevronLeft className="w-4 h-4" /> Back to Sessions
          </Link>
          <div className="flex items-center gap-3 mb-1">
            <div className="w-8 h-8 rounded-lg bg-[#9F7AEA]/20 flex items-center justify-center">
              <BarChart2 className="w-4 h-4 text-[#9F7AEA]" />
            </div>
            <h1 className="text-3xl font-bold text-[#EDF2F7]" style={{ fontFamily: "Fraunces, serif" }}>
              AI Session Feedback
            </h1>
          </div>
          <p className="text-[#A0AEC0]">Generated by AI after analyzing your session on <span className="text-[#EDF2F7]">{feedback.sessionTopic}</span></p>
        </div>

        {/* Overall Score */}
        <div className="glass-card rounded-2xl p-8 mb-6 text-center border border-[#9F7AEA]/20">
          <div className="text-sm text-[#A0AEC0] mb-2">Overall Session Score</div>
          <div className="text-7xl font-bold font-mono-jb mb-2" style={{ color: getScoreColor(feedback.overallScore) }}>
            {feedback.overallScore}
          </div>
          <div className="text-[#A0AEC0] text-sm">out of 100</div>
          <div className="mt-4 inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[#38A169]/20 border border-[#38A169]/30 text-[#38A169] text-sm font-medium">
            ✨ Great session! You're making solid progress
          </div>
        </div>

        {/* Score Cards */}
        <div className="grid md:grid-cols-3 gap-4 mb-6">
          {[
            { label: "Clarity Score", icon: <Target className="w-5 h-5" />, value: feedback.clarityScore, desc: "How clearly concepts were explained", color: "#2B6CB0" },
            { label: "Interaction Quality", icon: <MessageSquare className="w-5 h-5" />, value: feedback.interactionScore, desc: "Back-and-forth engagement level", color: "#D69E2E" },
            { label: "Engagement", icon: <TrendingUp className="w-5 h-5" />, value: feedback.engagementScore, desc: "Overall session energy and flow", color: "#38A169" },
          ].map((metric, i) => (
            <div key={i} className="glass-card rounded-2xl p-5">
              <div className="flex items-center gap-2 mb-3" style={{ color: metric.color }}>
                {metric.icon}
                <span className="text-sm font-medium text-[#EDF2F7]">{metric.label}</span>
              </div>
              <div className="text-3xl font-bold font-mono-jb mb-1" style={{ color: getScoreColor(metric.value) }}>
                {metric.value}<span className="text-base text-[#A0AEC0]">/100</span>
              </div>
              <div className="w-full bg-white/10 rounded-full h-1.5 mb-2">
                <div className="h-1.5 rounded-full" style={{ width: `${metric.value}%`, backgroundColor: getScoreColor(metric.value) }} />
              </div>
              <div className="text-xs text-[#A0AEC0]">{metric.desc}</div>
            </div>
          ))}
        </div>

        {/* Speaking Time Breakdown */}
        <div className="glass-card rounded-2xl p-6 mb-6">
          <div className="flex items-center gap-2 mb-4">
            <Mic className="w-5 h-5 text-[#63B3ED]" />
            <h2 className="text-lg font-semibold text-[#EDF2F7]" style={{ fontFamily: "Fraunces, serif" }}>Speaking Time Breakdown</h2>
          </div>
          <div className="flex gap-4 mb-4">
            <div className="flex-1 text-center glass-card rounded-xl p-4 border border-[#38A169]/20">
              <div className="text-3xl font-bold font-mono-jb text-[#38A169]">{feedback.speakingTimeThem}%</div>
              <div className="text-xs text-[#A0AEC0] mt-1">Teacher (them)</div>
            </div>
            <div className="flex items-center">
              <div className="text-[#A0AEC0] font-mono-jb text-sm">vs</div>
            </div>
            <div className="flex-1 text-center glass-card rounded-xl p-4 border border-[#2B6CB0]/20">
              <div className="text-3xl font-bold font-mono-jb text-[#63B3ED]">{feedback.speakingTimeMe}%</div>
              <div className="text-xs text-[#A0AEC0] mt-1">You (learner)</div>
            </div>
          </div>
          <div className="w-full h-4 rounded-full overflow-hidden flex">
            <div style={{ width: `${feedback.speakingTimeThem}%`, backgroundColor: "#38A169" }} className="h-full transition-all" />
            <div style={{ width: `${feedback.speakingTimeMe}%`, backgroundColor: "#2B6CB0" }} className="h-full transition-all" />
          </div>
          <div className="text-xs text-[#A0AEC0] mt-2 text-center">
            Duration: {feedback.duration} · Ideal ratio: 60% teacher / 40% learner
          </div>
        </div>

        {/* Key Points */}
        <div className="glass-card rounded-2xl p-6 mb-6">
          <div className="flex items-center gap-2 mb-4">
            <Lightbulb className="w-5 h-5 text-[#D69E2E]" />
            <h2 className="text-lg font-semibold text-[#EDF2F7]" style={{ fontFamily: "Fraunces, serif" }}>AI-Generated Key Points</h2>
            <div className="ml-auto flex items-center gap-1.5">
              <div className="w-2 h-2 rounded-full bg-[#9F7AEA] animate-pulse" />
              <span className="text-xs text-[#9F7AEA]">Auto-generated</span>
            </div>
          </div>
          <div className="space-y-2">
            {feedback.keyPoints.map((point, i) => (
              <div key={i} className="flex items-start gap-3 p-3 rounded-xl bg-white/3 hover:bg-white/5 transition-colors">
                <div className="w-5 h-5 rounded-full bg-[#D69E2E]/20 flex items-center justify-center shrink-0 mt-0.5">
                  <span className="text-[#D69E2E] text-xs font-bold">{i + 1}</span>
                </div>
                <p className="text-sm text-[#EDF2F7]">{point}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Improvement Tips */}
        <div className="glass-card rounded-2xl p-6 mb-6">
          <div className="flex items-center gap-2 mb-4">
            <TrendingUp className="w-5 h-5 text-[#38A169]" />
            <h2 className="text-lg font-semibold text-[#EDF2F7]" style={{ fontFamily: "Fraunces, serif" }}>Improvement Tips</h2>
          </div>
          <div className="space-y-3">
            {feedback.improvements.map((tip, i) => (
              <div key={i} className="flex items-start gap-3 p-3 rounded-xl" style={{ backgroundColor: i % 2 === 0 ? "rgba(43,108,176,0.1)" : "rgba(56,161,105,0.1)" }}>
                <span className="text-lg shrink-0">{i === 0 ? "💡" : i === 1 ? "🎯" : i === 2 ? "✅" : "📝"}</span>
                <p className="text-sm text-[#A0AEC0] leading-relaxed">{tip}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Actions */}
        <div className="flex gap-3">
          <Link href="/dashboard/sessions" className="flex-1 py-3 glass-card text-[#EDF2F7] rounded-xl font-medium hover:bg-white/10 transition-colors text-center">
            Back to Sessions
          </Link>
          <Link href="/dashboard/sessions/book" className="flex-1 py-3 bg-[#2B6CB0] hover:bg-[#2C5282] text-white rounded-xl font-medium transition-colors text-center">
            Book Another Session
          </Link>
        </div>
      </main>
    </div>
  );
}
